import { createRef, useContext, useEffect } from "react";
import useSWR from "swr";
import type { NextPage } from "next";
import fsPromises from "fs/promises";
import path from "path";
import Head from "next/head";
import Image from "next/image";

import VerticalSpacing, {
  SpacingSizes,
} from "../components/base/Spacing/VerticalSpacing";
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import QuoteBox from "../components/QuoteBox/QuoteBox";
import ContactForm from "../components/ContactForm/ContactForm";
import HeroSection from "../components/HeroSection/HeroSection";
import Carousel from "../components/Carousel/Carousel";
import CardsGrid from "../components/CardsGrid/CardsGrid";

import content from "./api/EvopackContent.json";

import styles from "../styles/Home.module.css";
import GlobalContext from "../contexts/GlobalContext";

import { wData } from "../data";

const fetcher = (url: any) => fetch(url).then((res) => res.json());

type NextProps = {
  data?: any;
  error?: any;
};

const Home: NextPage = (props: any) => {
  // const contentData: any = content;

  // const { data, error } = useSWR("/api/staticdata", fetcher);
  // const { data, error } = props;

  const { language } = useContext(GlobalContext);

  const languageSpecificContent = props[language].home;

  // const languageSpecificContent = content[language].home;

  const { hero, cardsGrid, quote, carousel, contactForm } =
    languageSpecificContent;

  const contactRef = createRef<HTMLDivElement>();

  function handleBackClick(ref: any) {
    if (ref && ref.current /* + other conditions */) {
      ref.current.scrollIntoView({ behavior: "smooth", block: "end" });
    }
  }

  useEffect(() => {
    document.documentElement.scrollTop = 0;
  }, []);

  //Handle the error state
  if (!props) return <div>Failed to load data..</div>;
  //Handle the loading state
  // if (!data) return <div>Loading...</div>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Evopack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <HeroSection
        data={hero}
        handleCTAClick={() => {
          handleBackClick(contactRef);
        }}
      />
      <CardsGrid data={cardsGrid} />
      <QuoteBox
        text={quote.text}
        author={quote.author}
        authorTitle={quote.authorPosition}
      />
      <Carousel data={carousel} />
      <VerticalSpacing size={SpacingSizes.xl40px} />
      <VerticalSpacing size={SpacingSizes.xl40px} />

      <ContactForm ref={contactRef} />
      <Footer />
    </div>
  );
};

export const getStaticProps = async () => {
  return {
    props: wData,
  };
};

export default Home;
